services:
    app:
        build:
            context: .
            dockerfile: Dockerfile        
        container_name: ${APP_NAME}
        restart: unless-stopped
        user: "${UID:-1000}:${GID:-1000}"
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker-config/php/up-config.ini:/usr/local/etc/php/conf.d/up-config.ini
        networks:
            - app-network
    nginx:
        image: nginx:alpine
        container_name: nginx-${APP_NAME}
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-config/nginx:/etc/nginx/conf.d
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
