upload_max_filesize=50M
post_max_size=50M
memory_limit=1G
max_execution_time=600
default_socket_timeout=3600
request_terminate_timeout=600

; Desativa a validação de timestamp ou coloca frequencia 0
opcache.enable=1
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_accelerated_files=10000
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1